# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\view.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1280, 800)
        self.player_plain_text = QtWidgets.QPlainTextEdit(Form)
        self.player_plain_text.setGeometry(QtCore.QRect(640, 716, 140, 41))
        self.player_plain_text.setPlainText("")
        self.player_plain_text.setObjectName("player_plain_text")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(640, 680, 121, 41))
        self.label.setStyleSheet("")
        self.label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label.setLineWidth(1)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setScaledContents(False)
        self.label.setObjectName("label")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(90, 70, 1081, 401))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(37)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_1 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_1.setAutoFillBackground(False)
        self.label_1.setStyleSheet("background:white")
        self.label_1.setText("")
        self.label_1.setObjectName("label_1")
        self.horizontalLayout.addWidget(self.label_1)
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_2.setAutoFillBackground(False)
        self.label_2.setStyleSheet("background:white")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(90, 520, 399, 121))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(4)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btn_open = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.btn_open.setObjectName("btn_open")
        self.horizontalLayout_5.addWidget(self.btn_open)
        self.btn_save = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.btn_save.setEnabled(False)
        self.btn_save.setObjectName("btn_save")
        self.horizontalLayout_5.addWidget(self.btn_save)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(0, -1, -1, 0)
        self.horizontalLayout_6.setSpacing(4)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.btn_play = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.btn_play.setEnabled(False)
        self.btn_play.setObjectName("btn_play")
        self.horizontalLayout_6.addWidget(self.btn_play)
        self.btn_quit = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.btn_quit.setEnabled(True)
        self.btn_quit.setObjectName("btn_quit")
        self.horizontalLayout_6.addWidget(self.btn_quit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.pc_plain_text = QtWidgets.QPlainTextEdit(Form)
        self.pc_plain_text.setGeometry(QtCore.QRect(820, 716, 140, 41))
        self.pc_plain_text.setObjectName("pc_plain_text")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(820, 680, 121, 41))
        self.label_6.setStyleSheet("")
        self.label_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_6.setLineWidth(1)
        self.label_6.setTextFormat(QtCore.Qt.AutoText)
        self.label_6.setScaledContents(False)
        self.label_6.setObjectName("label_6")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_3.setEnabled(True)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(630, 520, 399, 121))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(4)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.btn_gray = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.btn_gray.setEnabled(False)
        self.btn_gray.setObjectName("btn_gray")
        self.horizontalLayout_7.addWidget(self.btn_gray)
        self.btn_soble = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.btn_soble.setEnabled(False)
        self.btn_soble.setObjectName("btn_soble")
        self.horizontalLayout_7.addWidget(self.btn_soble)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(0, -1, -1, 0)
        self.horizontalLayout_8.setSpacing(4)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.btn_binary = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.btn_binary.setEnabled(False)
        self.btn_binary.setObjectName("btn_binary")
        self.horizontalLayout_8.addWidget(self.btn_binary)
        self.btn_find_contours = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.btn_find_contours.setEnabled(False)
        self.btn_find_contours.setObjectName("btn_find_contours")
        self.horizontalLayout_8.addWidget(self.btn_find_contours)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.result_plain_text = QtWidgets.QPlainTextEdit(Form)
        self.result_plain_text.setGeometry(QtCore.QRect(1000, 710, 140, 41))
        self.result_plain_text.setObjectName("result_plain_text")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(1000, 674, 121, 41))
        self.label_7.setStyleSheet("")
        self.label_7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_7.setLineWidth(1)
        self.label_7.setTextFormat(QtCore.Qt.AutoText)
        self.label_7.setScaledContents(False)
        self.label_7.setObjectName("label_7")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "手部辨識 - 猜拳遊戲"))
        self.label.setText(_translate("Form", "你出的是："))
        self.btn_open.setText(_translate("Form", "Open"))
        self.btn_save.setText(_translate("Form", "Save"))
        self.btn_play.setText(_translate("Form", "Play"))
        self.btn_quit.setText(_translate("Form", "Quit"))
        self.label_6.setText(_translate("Form", "電腦出的是："))
        self.btn_gray.setText(_translate("Form", "Gray"))
        self.btn_soble.setText(_translate("Form", "Soble"))
        self.btn_binary.setText(_translate("Form", "Binary"))
        self.btn_find_contours.setText(_translate("Form", "FindContours"))
        self.label_7.setText(_translate("Form", "結果："))


